config/routes.rb
TicktrProject::Application.routes.draw do
  resources :preferences

  resources :users

  root to: 'users#new'
  

end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :user
end

app/models/seat_geek_api_connect.rb
class SeatGeekApiConnect
# import datetime, dateutil.parser
  attr_accessor :events


  def initialize(postal_code)
    @postal_code = postal_code
  end

  def get_events
    formatted_events = []
    until formatted_events.empty? == false
      @event_type = %w(sports concerts baseball theater soccer basketball band nba mlb mls nhl boxing monster_truck).sample
      @events = SeatGeek::Connection.events({:type => "#{@event_type}", :postal_code => @postal_code})
      @events["events"].each do |event|
        @event_datetime = []
        @event_datetime << event["datetime_local"].to_date.strftime("%A %m/%d/%y") << event["datetime_local"].to_datetime.strftime("%l:%M %p")
        formatted_events << {:url => event["url"], :title => event["title"], :time => "#{@event_datetime.to_s.gsub!('"','').gsub!('[','').gsub!(']','').gsub!(',',' at')}"}
      end
    end
    formatted_events
  end
end

app/models/seatgeek.rb
class SeatGeekApiConnect





end

SeatGeek::Connection.events({:type => "concert"})
SeatGeek::Connection.events({:type => "baseball"})
SeatGeek::Connection.events({:type => "sports"})
SeatGeek::Connection.events({:type => "theater"})
SeatGeek::Connection.events({:type => "hockey"})
SeatGeek::Connection.events({:type => "basketball"})
SeatGeek::Connection.events({:type => "soccer"})

app/models/user.rb
require 'pry'
class User < ActiveRecord::Base

  validates_format_of :postal_code,
   :with => /\A\d{5}-\d{4}|\A\d{5}\z/, 
   :message => "not valid"

	# def like(event_type)
	# 	if event_type == "concert"
	# 		self.concerts += 1
	# 	elsif event_type == "sports"
	# 		self.sports += 1
	# 	end
	# 	self.save
	# end

	# def dislike(event_type)
	# 	if event_type == "concert"
	# 		self.concerts -= 1
	# 	elsif event_type == "sports"
	# 		self.sports -= 1
	# 	end
	# 	self.save
	# end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :url, :postal_code, :type)
    end
end

app/controllers/users_controller.rb
  class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @seatgeek = SeatGeekApiConnect.new(@user.postal_code)
    @events = @seatgeek.get_events
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    # respond_to do |format|
      if @user.save
        redirect_to @user
      else
        @user.save
        render 'new'
      end
    rescue ActiveRecord::RecordInvalid
      flash[:error] = "oops"
      render :action => :new
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :postal_code)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/preferences_helper.rb
module PreferencesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :postal_code %><br>
    <%= f.number_field :postal_code %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th>Postal code</th>
      <th>Type</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.url %></td>
        <td><%= event.postal_code %></td>
        <td><%= event.type %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @event.url %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @event.postal_code %>
</p>

<p>
  <strong>Type:</strong>
  <%= @event.type %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/_footer.html.erb
<div class="footer push">
 <text style="size: 2px">.</text>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<!-- <%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%#= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>
 -->
<div class="navbar navbar-fixed-top navbar-default">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <div class="navbar-collapse collapse navbar-responsive-collapse">
    <ul class="nav navbar-nav">
    <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<%= link_to 'Home', root_path, class: 'navbar-brand' %> 

<%= link_to 'Past Searches', '/users' , class: 'navbar-brand' %> 

<%= link_to 'The Original', 'http://seatgeek.com/', class: 'navbar-brand', :target => "_blank" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Ticktr Project" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Ticktr Project" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body class="background-color-auto">
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main" class="wrapper">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
  
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> </h2>

      <p>
      <% @user.errors.full_messages.each do |msg| %>
        <%= msg %>
      <% end %>
      </p>
    </div>
  <% end %>

  <div class="field form-group" id="slate">
    <%= f.label "Enter your ZIP code", class: "control-label"%><br>
    <%= f.text_field :postal_code, class: "form-control"%>
  </div>

<!--   <div class="form-group">
    <label class="control-label" for="inputDefault">Default input</label>
    <input type="text" class="form-control" id="inputDefault">
  </div> -->

  <div class="actions">
    <input type="submit" class="btn btn-default" value="Find me some tickets">
</div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<center><h1>Places You've Looked</h1>
  <h4> By ZIP </h4>

<table>
  <thead>
    <tr>
      <th class="zip-header"></th>
    </tr>
  </thead>


  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.postal_code %></td>
        <td><%= link_to 'See Events', user %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Search', new_user_path %>

</center>

app/views/users/new.html.erb
<center><h1 id="slate">Welcome to Ticktr</h1>
<h3 id="slate">Tickets to Random Events in Your Area</h3>

<%= render 'form' %>
</center>

app/views/users/show.html.erb
<center><p id="notice"><%= notice %></p>

<p>
  <h3>So you live in <%= @user.postal_code %> ? </br></h3>
    <h4>THESE EVENTS ARE IN YOUR AREA:</h4>  
  </br>
  

</p>

<table>
  <thead>
    <tr>
      <th class="zip-header"></th>
    </tr>
  </thead>
  <tbody>
  	<% @events.each do |event| %>
  	<tr class="spaceUnder">
  		<td><%= link_to event[:title], event[:url]%></br></td>
  		<td><%=event[:time] %> <% end %></td>
  	</tr>
  </tbody>
</table>

<p> 

</br>

 

</br>


<text style="font-size:12pt;">Interested in any of these events?</text>
</br>
</br>
<h4>CLICK THE LINK AND BUY THE TICKETS</h4>
</p>

<FORM>
	<INPUT TYPE="button" class="btn btn-default" onClick="history.go(0)" VALUE="No thanks. Got anything else?" style="margin-bottom:20px">
</FORM>


<%= link_to 'Hold on...this isn\'t my area', new_user_path(@user), class: "btn btn-default btn-sm" %> |
<%= link_to 'Where did I look for tickets again?', users_path, class: "btn btn-default btn-sm" %></center>